### ISSUE TITLE
D2X Page-In breakpoint trap upon levelchange

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#221]
I discovered quite an interesting issue today as I was playtesting Descent 2.

The steps to re-produce this are as follows:
1) Launch D2X.
2) With a player that already once played all the missions (can be done via FREEESPACE cheat) launch LEVEL 10 of the original Descent 2 campaign via NEW GAME.
3) After loading LEVEL 10, quit to main menu.
4) Now select NEW GAME again and this time load up LEVEL 11. 

This triggers the following breakpoint: 

```
Thread 1 "d2x-rebirth" received signal SIGTRAP, Trace/breakpoint trap.
0x00000000004b0049 in dcx::d_debugbreak () at common/include/dxxerror.h:123
123             DXX_DEBUGBREAK_TRAP();
(gdb) bt
#0  0x00000000004b0049 in dcx::d_debugbreak () at common/include/dxxerror.h:123
#1  d2x::piggy_bitmap_page_in (bitmap=...) at similar/main/piggy.cpp:1377
#2  0x00000000004abaeb in d2x::_piggy_page_in (bmp=...) at common/main/piggy.h:137
#3  paging_touch_walls () at similar/main/paging.cpp:311
#4  d2x::paging_touch_all () at similar/main/paging.cpp:329
#5  0x00000000004b00b5 in piggy_load_level_data () at similar/main/piggy.cpp:1478
#6  0x000000000045e0c8 in d2x::LoadLevel (level_num=level_num@entry=11, page_in_textures=1) at similar/main/gameseq.cpp:803
#7  0x000000000045fad6 in d2x::StartNewLevelSub (level_num=level_num@entry=11, page_in_textures=page_in_textures@entry=1, secret_flag=secret_flag@entry=d2x::secret_restore::none) at similar/main/gameseq.cpp:1609
#8  0x000000000045feee in d2x::StartNewLevel (level_num=level_num@entry=11) at similar/main/gameseq.cpp:1841
#9  0x000000000045ff47 in d2x::StartNewGame (start_level=start_level@entry=11) at similar/main/gameseq.cpp:867
#10 0x000000000047bd18 in do_new_game_menu () at similar/main/menu.cpp:852
#11 0x000000000048616e in mission_menu_handler (lb=<optimized out>, event=..., mm=0x4d260f0) at similar/main/mission.cpp:1033
#12 0x00000000004a5f66 in listbox_key_command (lb=0x464c870, event=...) at similar/main/newmenu.cpp:1861
#13 listbox_handler (wind=<optimized out>, event=..., lb=0x464c870) at similar/main/newmenu.cpp:2062
#14 0x0000000000411a10 in dcx::window_send_event (wind=..., event=...) at common/arch/sdl/window.cpp:211
#15 0x000000000040ff8b in dcx::event_send (event=...) at common/arch/sdl/event.cpp:132
#16 0x0000000000411290 in dcx::key_handler (kevent=kevent@entry=0x7fffffffe480) at common/arch/sdl/key.cpp:453
#17 0x000000000041019a in dcx::event_poll () at common/arch/sdl/event.cpp:47
#18 0x00000000004101d8 in dcx::event_process () at common/arch/sdl/event.cpp:154
#19 0x000000000040a74b in d2x::main (argv=<optimized out>, argc=<optimized out>) at similar/main/inferno.cpp:589
#20 main (argc=<optimized out>, argv=<optimized out>) at similar/main/inferno.cpp:627
```

I assume this may be a very old bug (I have not bisected it) which now shows due to Int3 actually triggering.

**Comment by vLKp** [comment]
This seems not to occur with the latest code.  It was likely fixed by reverting the removal of paging support.
