### ISSUE TITLE
Runtime bug: Host left the game

### ISSUE THREAD

**Issue by snytek** [dxx-rebirth/dxx-rebirth#520]
### Environment

https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20200630-win.zip

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

This issue occurs in different 1-level missions or in the last level of a set.

### Description

A multiplayer game (1 level mission) is started and clients join (internet with port forwarding).
Reactor is blown, countdown starts
Either the host leaves the mine by entering the exit or gets killed on the way he gets to the summary screen.
At the bottom the the countdown is still visible and counting down about 5 seconds but then suddenly stops. 
Alle clients get the message "Host left the game"

#### Regression status

Unknown.

### Steps to Reproduce

For reproducing steps see my description.
It happens all the time and should be easy to reproduce.

* Engines affected:
  * [ ] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [X] Multiplayer competitive
    * [X] Anarchy
    * [ ] Team Anarchy  <- not tested
    * [ ] Robo-Anarchy  <- not tested
    * [X] Capture the Flag
    * [X] Bounty
  * [ ] Multiplayer cooperative <- not tested

**Comment by vLKp** [comment]
This probably impacts all multiplayer modes.  The loss of statistics is unfortunate, and worth fixing, but unless this turns out to be very easy to fix, it will likely not get fixed very soon.

**Comment by MasonP57** [comment]
I can confirm that this affects all multiplayer issues. I played Rebirth 0.61 anarchy, with the Kill Limit option enabled. After we finished our game and all the survivors reached the exit, all the non-host clients crashed.

**Comment by vLKp** [comment]
The original report says the clients get a message that the host left.  It said nothing about a crash.  Were you able to collect a backtrace from the crash?

**Comment by MasonP57** [comment]
I will try to test it again and see. I don't know what a backtrace is.

**Comment by snytek** [comment]
I have to confirm that we also encounter occasional application crashes (some get the message 'host left the game' other directly crash). The crashes don't happen every time and is thus hard to reproduce. We don't have any logs yet.

What do we need to do to provide you with the desired output? Is it enough to enable -debug and -verbose in the d2x.ini?

BTW: as the game statistics doesn't get saved properly if the game crashes we now usually exit "gracefully" -> each client quits the game manually before the host kills the reactor and exists the game to get the score summary...

**Comment by vLKp** [comment]
@snytek wrote:
> @vLKp wrote:
> > Ideally, you would provide steps to reproduce readily, or failing that, provide a crash dump.
> 
> Well, I think the steps are already documented above and work every time with my setup.
> Were you able to follow my steps to reproduce the crash?

The steps in the opening post only discuss a "Host has left the game" failure mode.  While unfortunate, that is not a high priority for me to investigate, because the network code has not changed in a long time, and has a significant amount of global state.

Your later post, where you mention the intermittent crash, specifically stated it was intermittent.  I have very limited time to chase bug reports, so I prefer not to spend it chasing problems specifically characterized as intermittent.

> > This is unfortunate, as it makes identifying the problem harder.
> 
> So, probably additional log messages for the `verbose` mode would have to be implemented to get more information to narrow down the location and/or situation, right?

Correct.  If I knew where to put them, I would have a good idea about where to debug to fix the problem.  With the information available, I don't have a good idea about where to put them, so I don't have any suggestions on where to log more.  A crash dump, if one could be acquired, would give me a full snapshot of the program state, without requiring me to identify in advance which areas of the program are most likely to be interesting.

> > What do you mean here? You crossed the exit door, and instead of exiting the mine, you just kept flying until you reached the end of the exit tunnel, as would happen if the level author failed to mark the exit door as an exit?
> 
> Well, this was weired. As I wrote, the host showed the summary screen and the client got the message and crashed so my focus was on the client. When I looked back at the host screen I was back in the level again (at the point where I left the mine through the exit) and yes, I could fly through the exit as if it wasn't flagged as exit and could fly to the last cube of the corridor (which was completely black). I could do this several times.
> The 2 player names in the left lower corner (host and client) were both gray, indicating that both left the level. It felt like I was a ghost.
> 
> This only happend once (out of 3 tries) but could perhaps indicate where the problem could be located - that's why I mentioned it.

There is a known issue that `event_process_all` gets confused and produces very odd results if a message box interrupts an inter-level interstitial.  It produces similar results.  The player is dropped into a level that is flashing as if a reactor countdown were running, but the level never expires.  When the player quits the game (expecting to return to the main menu), they instead advance to the next level of the campaign, as should have happened automatically and in place of leaving them in the ghost level.

Fixing that issue properly is invasive.  A spot fix may be possible, but I've never had a report of this from a user.  If I remember the call chain correctly, level-loading code calls into multiplayer code for networking reasons, which calls into GUI code, which ends up running a half-loaded level.  The layering violations here are impressive.

> > Is the reproduction scenario above a crash or merely the "Host has left" case? Is it special to Pyroglyphic? If yes, where can I find that level?
> 
> No it isn't. As I wrote, it always occurrs in the last level of a mission set.
> A minute ago I could reproduce it with the Pandemonium mission (level 6):

I strongly prefer failures in the retail campaign levels, when they are reproducible there.  I can work with failures elsewhere though.

>     * Host: starts game
> 
>     * Client: joins
> 
>     * Client: destroys reactor
> 
>     * Client: exits the mine (and gets 'host left the game' followed by a crash)

That sounds promising.

>     * Host: exits the mine (and gets back to the main menu)
> 
> I even tried to create new player profiles for client and server as I thought this might be the cause but also with the new players I could reproduce the crash.

That was a good thought, but I expect it would be fairly rare that a player profile could be corrupt in a way that was not immediately fatal.

> I'd like to help narrow down the bug with testing but, as I already mentioned in other tickets, I am not able to compile a certain version from GitHub.
> Here I would need someone doing that for me - or providing e.g. a Virtual Box image where everything is setup correctly (dependencies, libraries, configuration, ect).

Noted.  I do not have VirtualBox installed, nor anywhere to host an image if I were to create one.  That is why I elected to provide instructions on how users can build the code for themselves.

I will try to reproduce the crash.

**Comment by vLKp** [comment]
The good news is that the crash was easy to reproduce.  The bad news is that it appears to be a variant of the problem I described above, where the game keeps running, then the level that just finished continues to play with partially invalid data.

```
#0  0x000055555558a507 in dcx::window_send_event (event=..., wind=...) at common/include/window.h:171
#1  dcx::WINDOW_SEND_EVENT (file=0x5555556c16ce "common/arch/sdl/window.cpp", line=97, event=..., w=...) at common/include/window.h:171
#2  dcx::window_close (wind=wind@entry=0x555556ad3d20) at common/arch/sdl/window.cpp:97
#3  0x0000555555587e10 in dcx::window_send_event (event=..., wind=...) at common/include/window.h:118
#4  dcx::event_process () at common/arch/sdl/event.cpp:247
#5  0x00005555555ecd35 in dcx::event_process_all () at common/include/event.h:138
#6  kmatrix_view (network=<optimized out>) at similar/main/kmatrix.cpp:417
#7  0x000055555560d1a8 in d2x::multi_endlevel_score () at similar/main/multi.cpp:453
#8  0x00005555555dabd4 in d2x::DoEndGame () at similar/main/gameseq.cpp:1645
#9  0x00005555555de845 in d2x::AdvanceLevel (secret_flag=<optimized out>) at similar/main/gameseq.cpp:1707
#10 0x00005555555de8e1 in d2x::PlayerFinishedLevel (secret_flag=secret_flag@entry=0) at similar/main/gameseq.cpp:1593
#11 0x00005555555ba448 in d2x::start_endlevel_sequence () at similar/main/endlevel.cpp:390
#12 0x00005555555aee5e in d2x::do_final_boss_frame () at similar/main/collide.cpp:1387
#13 0x00005555555c75fe in d2x::GameProcessFrame () at similar/main/game.cpp:1784
#14 d2x::game_handler (event=...) at similar/main/game.cpp:1624
#15 0x0000555555587dd0 in dcx::window_send_event (event=..., wind=...) at common/include/window.h:116
#16 dcx::event_process () at common/arch/sdl/event.cpp:247
#17 0x00005555555ecd35 in dcx::event_process_all () at common/include/event.h:138
#18 kmatrix_view (network=<optimized out>) at similar/main/kmatrix.cpp:417
#19 0x000055555560d1a8 in d2x::multi_endlevel_score () at similar/main/multi.cpp:453
#20 0x00005555555dabd4 in d2x::DoEndGame () at similar/main/gameseq.cpp:1645
#21 0x00005555555de845 in d2x::AdvanceLevel (secret_flag=<optimized out>) at similar/main/gameseq.cpp:1707
#22 0x00005555555de8e1 in d2x::PlayerFinishedLevel (secret_flag=secret_flag@entry=0) at similar/main/gameseq.cpp:1593
#23 0x00005555555ba448 in d2x::start_endlevel_sequence () at similar/main/endlevel.cpp:390
#24 0x00005555555aee5e in d2x::do_final_boss_frame () at similar/main/collide.cpp:1387
#25 0x00005555555c75fe in d2x::GameProcessFrame () at similar/main/game.cpp:1784
#26 d2x::game_handler (event=...) at similar/main/game.cpp:1624
```

Note how frame `#13` re-enters the game processing logic while displaying the score screen (frame `#18`).  Nothing good is likely to come of this, and I suspect if the game had not crashed, we would see further recursion from the inner call to `event_process_all`.

**Comment by snytek** [comment]
I am very happy that you are one step further. 
Now comes the difficult part...

**Comment by vLKp** [comment]
Yes.  Fixing this properly is invasive.  In my opinion, it is fundamentally wrong that drawing one window can cause the game to sleep, which causes the game to do networking as it sleeps, which causes another window to appear, which requires a window processing loop, which tries to draw the window that is already busy sleeping.  I may be able to prevent the crash by changing the object ownership rules to prevent premature destruction of the window.

**Comment by MasonP57** [comment]
I would like to chip in, that I played co-op yesterday in Descent 1 with the latest code compiled (compiled August 29th) and no one crashed when seeing the level results screen.

He was playing Linux, I was playing Windows. I'm not sure if this is a factor, as the above easily-reproducible crash is something I've seen when everyone involved had a Windows machine.

**Comment by vLKp** [comment]
The host crash (but not the guest crash) can be prevented by reverting 2bed74b05649d9d3350875ba90534a1903df3ea6 (which must be reverted by hand because the code has changed since then).  There are probably side effects to reverting this, so it is mainly of interest as an explanation for how this broke.

I am disappointed that reverting this fixes only one crash, as it suggests there are multiple object ownership bugs lurking here.

The fault I am examining is caused by a double-free due to convoluted object ownership rules in the GUI code.  A double-free may, or may not, crash the program, depending on the consequences of the corruption it causes.  When the program is built with AddressSanitizer, the double-free is trapped and converted into a hard crash at the site of the second free, rather than waiting for the corruption to cause problems later.

Linux may well have a different reaction to the corruption than Windows does.  It's surprising, but not impossible, that even the Windows users avoided a crash in that case.

**Comment by MasonP57** [comment]
I would like to chip in, that I played co-op 2 days ago in Descent 1 with the latest code compiled (compiled August 29th) and no one crashed when seeing the level results screen.

He was playing Linux, I was playing Windows. I'm not sure if this is a factor, as the above easily-reproducible crash is something I've seen when everyone involved had a Windows machine.

**Comment by BenMcLean** [comment]
I ran into this as well. Really sucks.

**Comment by vLKp** [comment]
I am working on this, but as I said above, the proper fix is invasive.  I think the specific crash described above is fixed in my local tree, but I am trying to clean up the general design.

**Comment by vLKp** [comment]
I pushed a long series of changes recently which should address this, among other problems.  I ultimately decided not to fix the entire design, but did make substantial progress on it.  I have not ruled out finishing the design change later.

For the purpose of this ticket, I made two important changes:
- In the build for which this was reported, the game always advances after a level is completed.  With the recent changes, the game will not force the user to advance after the last level of a mission is completed, since the only place to go is back to the main menu.
- In the reported build, the score window always frees itself after a timer elapses.  This led to a double-free in the reported scenario.  A double-free is **always** a bug, and can crash the program.  I changed the logic so that the score window can only free itself if it is in the foreground.  This way, if the user has some other window, such as "The host has left the game" in front of the score window, the score window will linger until that other window is closed.  When the score window is freed while in the foreground, it should immediately become unreachable and thus not able to be freed again later.  This has the slight negative consequence that if the host places the score window in the background on a level other than the last, then the host can delay entering the next level, which may surprise guests.  In testing, this did not cause any negative effect on the game.
-- Due to the change to remove the forced advance, the host may not leave the game as soon, which would have reduced, but not eliminated, the problem.
- I reverted 2bed74b as described in my prior comment.  I think it caused more problems than it solved.

@snytek, @BenMcLean: please sync to the latest code, build, and try it out.  The bad builds should crash on finishing a mission, regardless of how many levels are in the mission or were played.  Therefore, you should able to start a game directly on the last level of a mission, win that level, and see the result.  (Assuming that the last level is not so difficult that a cold start is impossible to win, of course. ;))  When I tried this, the game was stable with the changes I posted recently.  If either of you still see a crash, please reopen.

**Comment by snytek** [comment]
@vLKp: I'm afraid we have to reopen this issue :-/. Seems I am not able to do this on my own.

We have downloaded the latest Windows build (1afd0ee, 2021/01/26) from dxx-rebirth.com and played some matches. I was hosting the game and at the end of a one level mission my friends reported that the game crashed on their sides...

My ovservations (inhouse test with 2 PCs):

Test 1:
- Player 1 starts game
- Player 2 joins
- Player 1 kills reactor and gets to summary screen
- Countdown for Player 2 is counting
- About 7 seconds Plaxer 2 gets message "Host left the game" and is thrown back to main menu (no crash)

Test 2:
- Player 1 starts game
- Player 2 joins
- Player 1 kills reactor 
- Player 2 exits mine and gets to summary screen
- About 5-7 seconds later he gets message "Host left the game" and the game crashes (first freeze then exit to Windows)
- Player 1 is able to leave the mine, gets to the summary - everything is fine

This is the lower part of the gamelog.txt of Test 2 (I think this is the interesting part):

```
17:41:20.702 P#1: Removing stored pkt_num [2,0,0,0,0,0,0,0] - missing ACKs: 0
17:41:22.661 AFTERBURNER!
17:41:22.661 P#1: Adding MData pkt_num [3,1,1,1,1,1,1,1], type 8 from P#1 to MData store list
17:41:22.663 P#1: Got MData ACK for pkt_num 3 from pnum 0 for pnum 1
17:41:22.665 P#1: Removing stored pkt_num [3,0,0,0,0,0,0,0] - missing ACKs: 0
17:41:29.844 P#1: Adding MData pkt_num [4,1,1,1,1,1,1,1], type 54 from P#1 to MData store list
17:41:29.861 P#1: Got MData ACK for pkt_num 4 from pnum 0 for pnum 1
17:41:29.862 P#1: Removing stored pkt_num [4,0,0,0,0,0,0,0] - missing ACKs: 0
17:41:32.859 P#1: Adding MData pkt_num [5,1,1,1,1,1,1,1], type 54 from P#1 to MData store list
17:41:32.863 P#1: Got MData ACK for pkt_num 5 from pnum 0 for pnum 1
17:41:32.865 P#1: Removing stored pkt_num [5,0,0,0,0,0,0,0] - missing ACKs: 0
17:41:36.140 P#1: Adding MData pkt_num [6,1,1,1,1,1,1,1], type 54 from P#1 to MData store list
17:41:36.142 P#1: Got MData ACK for pkt_num 6 from pnum 0 for pnum 1
17:41:36.144 P#1: Removing stored pkt_num [6,0,0,0,0,0,0,0] - missing ACKs: 0
17:41:37.156 P#1: Adding MData pkt_num [7,1,1,1,1,1,1,1], type 54 from P#1 to MData store list
17:41:37.175 P#1: Got MData ACK for pkt_num 7 from pnum 0 for pnum 1
17:41:37.177 P#1: Removing stored pkt_num [7,0,0,0,0,0,0,0] - missing ACKs: 0
17:41:49.318 The main reactor has been destroyed!
17:41:49.318 P#1: Adding MData pkt_num [8,1,1,1,1,1,1,1], type 44 from P#1 to MData store list
17:41:49.335 P#1: Got MData ACK for pkt_num 8 from pnum 0 for pnum 1
17:41:49.335 P#1: Removing stored pkt_num [8,0,0,0,0,0,0,0] - missing ACKs: 0
17:41:50.981 P#1: Sending MData ACK for pkt 15 by pnum 0
17:41:51.925 P#1: Sending MData ACK for pkt 16 by pnum 0
17:41:57.598 P#1: Adding MData pkt_num [9,1,1,1,1,1,1,1], type 54 from P#1 to MData store list
17:41:57.602 P#1: Got MData ACK for pkt_num 9 from pnum 0 for pnum 1
17:41:57.604 P#1: Removing stored pkt_num [9,0,0,0,0,0,0,0] - missing ACKs: 0
17:41:57.932 P#1: Adding MData pkt_num [10,1,1,1,1,1,1,1], type 53 from P#1 to MData store list
17:41:57.935 P#1: Got MData ACK for pkt_num 10 from pnum 0 for pnum 1
17:41:57.937 P#1: Removing stored pkt_num [10,0,0,0,0,0,0,0] - missing ACKs: 0
17:41:58.049 You have escaped the mine!
17:41:58.049 P#1: Adding MData pkt_num [11,1,1,1,1,1,1,1], type 12 from P#1 to MData store list
17:41:58.126 P#1: Got MData ACK for pkt_num 11 from pnum 0 for pnum 1
17:41:58.155 P#1: Removing stored pkt_num [11,0,0,0,0,0,0,0] - missing ACKs: 0
17:42:09.404 snytek has left the game!
17:42:09.404 P#1: Clearing trace list for 0
17:42:30.372 P#1: Adding MData pkt_num [1,1,1,1,1,1,1,1], type 0 from P#1 to MData store list
17:42:30.372 P#1: Adding MData pkt_num [1,1,1,1,1,1,1,1], type 7 from P#1 to MData store list
17:42:30.373 P#1: Removing stored pkt_num [0,0,0,0,0,0,0,0] - missing ACKs: 0
17:42:30.373 P#1: Removing stored pkt_num [0,0,0,0,0,0,0,0] - missing ACKs: 0
17:42:30.549 Flushed 2 UDP packets from socket 1916
```

**Comment by vLKp** [comment]
I am not able to test this just now, but reopening per request of original reporter.

**Comment by raptor** [comment]
This bug seems to be gone - I have been playing with Windows and Linux users (hosting on Linux) for a month or so now and no issues.

**Comment by vLKp** [comment]
That is good to see - but my recollection is that I also had no problems, even when others continued to report it as broken.  However, if I don't see any further reports of the problem in the next week or so, I will likely close this issue again.

**Comment by BenMcLean** [comment]
Unfortunately, this bug killed the interest in playing it in the friends I had to play it with years ago. I'd have to find somebody else who wants to play it to test again.

**Comment by vLKp** [comment]
I am sorry to see that.  This issue originally reported a problem with the level terminating early after the host escaped the last level of a mission.  While unfortunate, clients would lose all their state shortly anyway, since there is nowhere to go after the last level ends.  That, combined with the difficulty of testing multiplayer bugs that do not produce an instant crash, led to this being considered a low priority issue.  https://github.com/dxx-rebirth/dxx-rebirth/issues/520#issuecomment-675169974 seemed to report a different problem, as the original report was not a crash.  Your prior comment, https://github.com/dxx-rebirth/dxx-rebirth/issues/520#issuecomment-748554732, preceded my fix for that crash by about a week.  You never returned until now.  snytek did return, but again reported it to impact only the end of a mission.  Combined, there was no urgency to pursue this further.  If this is impacting levels other than the end of the mission, it is a serious problem that deserves quicker attention.

**Comment by BenMcLean** [comment]
> I am sorry to see that. This issue originally reported a problem with the level terminating early after the host escaped the last level of a mission. While unfortunate, clients would lose all their state shortly anyway, since there is nowhere to go after the last level ends. That, combined with the difficulty of testing multiplayer bugs that do not produce an instant crash, led to this being considered a low priority issue. [#520 (comment)](https://github.com/dxx-rebirth/dxx-rebirth/issues/520#issuecomment-675169974) seemed to report a different problem, as the original report was not a crash. Your prior comment, [#520 (comment)](https://github.com/dxx-rebirth/dxx-rebirth/issues/520#issuecomment-748554732), preceded my fix for that crash by about a week. You never returned until now. snytek did return, but again reported it to impact only the end of a mission. Combined, there was no urgency to pursue this further. If this is impacting levels other than the end of the mission, it is a serious problem that deserves quicker attention.

oh yeah please don't interpret what I said as a complaint. I really appreciate all work being done to keep Descent running on modern systems.

also, at the moment, I am interested in starting to get involved myself at least in providing Linux binaries that'll run on the Steam Deck.

**Comment by agibson2** [comment]
You can already install the latest dxx-rebirth linux binary natively on the Steam Deck very easily.  I am running it now thanks to a project called Luxtorpeda.  It runs great on Steam Deck.  Install Luxtorpeda from the Steam Deck desktop mode using Discovery app.  Then go into Steam and change compatibility to Luxtorpeda.  It will then launch the native Linux version that it downloads when you launch Descent 2 or 1 in Steam.  Multiplayer is compatible with those on Descent discord.

**Comment by BenMcLean** [comment]
hey thanks! since the web site only gave the source code for the linux version, I thought I had to build from source. Great to hear that it will be easier than I had anticipated.

**Comment by vLKp** [comment]
I was not aware that Luxtorpeda even exists.

I once experimented with doing a feature that could download levels from a central server.  I believe I never finished it, and abandoned it due to the difficulty of identifying a central server on which I could rely existing and offering service.  Providing level transfer over the game's own protocol is theoretically feasible, but I am not inclined to work on it in the foreseeable future.
